spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/expo
    url: jdbc:mysql://localhost:3306/shopping
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: common
    password: OperatorP0a7$5s0
#    username: expo
#    password: MSiynGLXzjFLNJJd
#    username: root
#    password: root
  data:
    redis:
      port: 6379
      host: localhost
#      password: 123456
      database: 1
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.quanweng.shopping
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8084
quanweng:
  upload:
    save-url: /var/www/shopImg/upload/
set:
  web:
    web-address: https://expo.butex.cn/#/pages/overlay/NameCard
qiniu:
  access-key: -QDPG5jFX2TqG--YX3OWjc_7gq4-FN3FTY5nB7Mx
  secret-key: ishe8elr5jN_9K4oYn1rWvNPxpy27ao-Q_qa5jk4
  bucket: exhibition-butex
  domain: https://file.butex.cn
siliconflow:
  api:
    url: https://api.siliconflow.cn/v1/chat/completions
    key: sk-plrzyxrkupcwemtsxqsedoxnjistmotrpjostuecynctrzhr
    model: deepseek-ai/deepseek-vl2
logging:
  level:
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.jdbc.datasource: DEBUG
